#version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
#    environment:
#      NODE_ENV: production
#      DB_HOST: database
#      DB_PORT: 3306
    depends_on:
      - database
  database:
    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: fastify_db
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
